"""empty message

Revision ID: 0a55c5deaf93
Revises: 
Create Date: 2023-09-07 12:03:01.545489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a55c5deaf93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=20), nullable=False))

    with op.batch_alter_table('text_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=20), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('text_message', schema=None) as batch_op:
        batch_op.drop_column('sender')

    with op.batch_alter_table('image_message', schema=None) as batch_op:
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
