"""empty message

Revision ID: b07062662509
Revises: 0a55c5deaf93
Create Date: 2023-09-07 15:33:06.749253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07062662509'
down_revision = '0a55c5deaf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_message', schema=None) as batch_op:
        batch_op.drop_column('prediction')

    # ### end Alembic commands ###
